export default {
  stickerOpen: false,
  mediaOptionsOpen: false,
  mediaType: null,
  imagePreview: false,
  replyState: false,
  mediaUploadState: false,
  scrollState: false,
  searchQuery: "",
  searchState: false,
  searchShow: false,
  statusState: false,
  previewType: null,
  renderstate: false,
  messageEdit: false,
  messageText: "",
  audioPlayState: null,
};
