export default {
  app_identifiers: ["com.srp_live"],
  api_token: "-lIPN9NGKvlJBI90zPVrFg",
  available_actions: [],
  domains: ["https://api.photoeditorsdk.com"],
  enterprise_license: true,
  expires_at: null,
  features: [
    "noexporttracking",
    "camera",
    "library",
    "export",
    "whitelabel",
    "customassets",
    "adjustment",
    "audio",
    "brush",
    "composition",
    "filter",
    "focus",
    "frame",
    "overlay",
    "sticker",
    "text",
    "textdesign",
    "transform",
    "trim",
    "videolibrary",
  ],
  issued_at: 1620753677,
  minimum_sdk_version: "1.0",
  owner: "img.ly GmbH",
  platform: "Android",
  products: ["vesdk"],
  version: "2.4",
  signature:
    "h3Q0G/1HZg+t9WXXYQ+b6YSbGHc3UOq1ktOci5tNf4xTV+A7igkTPCYbxSIELZUyAr+9idZNt8Z1thIVQ+3Kzaq7kCzaDgl+vHAglrxHTZuscg8gPjSGrfXWUeUNA0PZUXY72q5DYVc8BRaTrCdnIfZPScnvi1QmV/+M/ao2VGq98/Mu8jb4jHXpj3f/zTlsaBwUgLFCerR2nEYm8m0cpjxuGu1DSIKxCC8JgTxhPLC+w8LS0+gSlfps69lVUap7VyAj9DWCARQDfeHSAnokYzvTu0GL7xglCWuZbutaVezA//oWaa0qIDY66tOXBKosULRp2VqShATmfbvnIueAkEhWZSyMX+G6MRI1VYHtI4Q5YhMQLSWFvsIP6oVLJs+iiMpUXtcglGp85TGY9x2fQcJuWAbvFm7vYnTJqTHyiU81uZF+goC/N8zLrn8gORreOmdvDqQ7Sff65k8I9+D6cv7gtZGw4mxGohbMGqPuTFCXlbsCCA/58KTYJoqme/wPxqB0yhBE9VBU3W/y3TFjsv5ZmhZH1YheiN/fTOlnwSij8ZeaFCLtkNcfSmS7EWhPDWfZxptiRS7/BJqVRYxRwRc4W3KWMc30EiWCm0F+WDW64z0ayLH0g8KA56eaDR/8P1P0TNPJh8uS9t56HmvBmEU5pDrVm+BQRP3oPf3OFss=",
};
